### ISSUE TITLE
Problem when I hit "Open"

### ISSUE THREAD

**Issue by fullstack212** [learn-co-curriculum/looping-loop#10]
When I hit Open, the terminal opens and I get the following error:

Last login: Fri Nov  6 18:48:06 on ttys000
/tmp/tmp_open.sh ; exit;
[18:49:42] ~
// ♥ /tmp/tmp_open.sh ; exit;
Looking for lesson...
WARNING: You are attempting to open a lesson that is beyond your current lesson.
Are you sure you want to continue? [Yn]: y
Opening readme...
logout

[Process completed]
It also opens another tab that contains this error:
Lesson 'Looping Lab' is unpublished.

Thanks!

**Comment by AnnJohn** [comment]
Hi @fullstack212 please use the Ask a Question tool for immediate help to resolve your issue and someone from our support team will get back to you. Thanks.
