### ISSUE TITLE
LOOPING - LOOP CONSTRUCTOR

### ISSUE THREAD

**Issue by steadyonthego** [learn-co-curriculum/looping-loop#11]
This lesson did not open properly for me when I tried to fork the lab. It gives me this message in the terminal:

Looking for lesson...
WARNING: You are attempting to open a lesson that is beyond your current lesson.
Are you sure you want to continue? [Yn]: 

The following lesson opens properly.

**Comment by AnnJohn** [comment]
Yes @steadyonthego we recommend that you go in order with the curriculum but we will not stop you from going ahead. That's why the warning appeared.
