### ISSUE TITLE
Trouble Opening the Looping Lab

### ISSUE THREAD

**Issue by iSadia** [learn-co-curriculum/looping-loop#12]
Finished the previous lesson, made typical motions to commence next lesson using the Learn app. All seemed well-- the forking, the cloning-- but then received terminal warning that I am "attempting to open a lesson that is beyond your current lesson. Are you sure you want to continue? [Yn]"

I ignore the error and input "Y," but then am redirected to a page (https://learn.co/lessons/13157) that indicates that the Looping Lab has not yet been published. This page invites me to continue on to the next lesson-- the Looping Lab. Sending me into a loop of my own...

Have tried cloning and opening manually (i.e. via my terminal), but no dice.

**Comment by AnnJohn** [comment]
Hi @iSadia is this still an issue? If so, please use the Ask a Question tool in Learn and someone from our support team will get back to you. Thanks!
