### ISSUE TITLE
Lab repo can't be found

### ISSUE THREAD

**Issue by kvignali** [learn-co-curriculum/looping-loop#13]
When I click open on this lesson I get this: Looking for lesson... WARNING: You are attempting to open a lesson that is beyond your current lesson. Are you sure you want to continue? [Yn]: Y Opening readme... logout [Process completed] *Then it takes me to the learn website and says Lesson "Looping Lab" is unpublished

Screenshot from Nitrous:

![screen shot 2015-11-16 at 2 21 10 pm](https://cloud.githubusercontent.com/assets/2243896/11192150/5b695708-8c6d-11e5-8072-17b7ef75e617.png)

**Comment by AnnJohn** [comment]
@kvignali i think this is a product/labs issue. the repo was already published on our end. thanks

**Comment by AnnJohn** [comment]
closing this issue as it seems stale
