### ISSUE TITLE
Lesson is broken

### ISSUE THREAD

**Issue by NoelGSlater** [learn-co-curriculum/looping-loop#15]
Lesson lists itself as unpublished. It cannot be forked but not opened. 

It says WARNING: You are attempting to open a lesson that is beyond your current lesson.
Are you sure you want to continue? [Yn]: 

It doesnt make sense but even if I say Y it bring me to another screen that doesnt have a lesson. This should be looked at.

Thank you

**Comment by AnnJohn** [comment]
Hi @NoelGSlater this looks to be working on our end so it might be an issue specific to you. Please use the Ask a Question tool on Learn and someone from our support team will get back to you right away. Thanks!

**Comment by NoelGSlater** [comment]
Hi AnnJohn,

Its not actually working. I was able to directly clone the lab into my
repository but then when i go to push it says i dont have permission.
Please advise

Thanks

**Comment by NoelGSlater** [comment]
Its solved,

I was able to refork the file from scratch and reclone it and it accepted
the permissions this time

Thank you,

Noel Slater

**Comment by AnnJohn** [comment]
Great. Thanks!
