### ISSUE TITLE
"No spec file"

### ISSUE THREAD

**Issue by CodeByLine** [learn-co-curriculum/looping-loop#16]
There seem to be two versions of this exercise:

looping-loop-v-000   (which is what you get when clicking on Nitrous from the lesson)
    
   and

looping-loop-001-prework-web  (which is what I got if I click on GitHub from the lesson)

Problem is: looping-loop-v-000   doesn't run in Nitrous: "This directory doesn't appear to have any specs in it."

**Comment by AnnJohn** [comment]
Hi @CodeByLine there aren't any specs to this lesson which it says in the instruction portion of it. You should fork and clone the lesson, and both versions should be the same. Thanks!
