### ISSUE TITLE
Looping - Loop Constructor

### ISSUE THREAD

**Issue by theasteve** [learn-co-curriculum/looping-loop#18]
I have completed all the previous exercises and when I try to open this lab I get the following error.

>  You are attempting to open a lesson that is beyond your current lesson.
> Are you sure you want to continue? [Yn]:

When I press Y, it directs me to the Learn Web Development Fundamentals where it says:

> You do not have access to this lesson.

How can I fix this? I tried doing lessons over but still it doesn't let me open this lab. All the previous readings and exercises are complete.

**Comment by pletcher** [comment]
Thanks for opening this issue!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

Please be sure to include steps to reproduce (be as detailed as possible) and any relevant information about your environment. (Are you using the Learn IDE? Coding on a refurbished toaster?) We'll be sure to figure out what's going on — and to jump in and help — just as soon as we can. Thanks!

**Comment by rebeccayeyi** [comment]
SAME ISSUE. I've reported it as a bug directly & am hoping for a response soon b/c I would like to keep working!

**Comment by pletcher** [comment]
This is a product issue. Please raise an issue on the Learn platform (you can find the page for submitting an issue by clicking on your avatar in the upper right and then clicking "Report A Bug".
