### ISSUE TITLE
Control + C does not exit out of an infinite loop!

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/looping-loop#21]
Please update the README for this lab. Despite what the instructions say at the bottom, "Ctrl C" will not exit out of the infinite loop when you run "ruby looping.rb". As far as I can tell, the only way to exit out of the infinite loop is to refresh the page.

Thank you for looking into this!
Sdcrouse

**Comment by Sdcrouse** [comment]
Update: The problem appears to be caused by the terminal running the infinite loop too quickly. There simply isn't enough time to enter "Ctrl C" between one execution of the loop and the next, unless one holds down "Ctrl" and presses "C" as rapidly as possible.

One solution that I found when intentionally writing an infinite loop is to place a call to #sleep inside of the loop. That pauses the program long enough for the programmer to enter "Ctrl C" to exit out of it without any issues.

Again, thanks for looking into this!
Sdcrouse

**Comment by cjbrock** [comment]
Hey @Sdcrouse! You're right, it can be challenging to hit the exact right point in the infinite loop with ctrl+c to exit out of the loop. Pressing it rapidly is a good solution, as is writing a sleep method into the loop. The great thing about both of your solutions is that you're clearly researching outside out the Learn curriculum, which is an important skill to hone as a developer. The more code I write, the better I get at Googling things! Keep up the great work. 
// Corinna
